[path]
download_path: ./contrib/99991/downloads/
processed_path: ./processed

[dataset]
dataset_type_help: dataset_full, dataset_small, dataset_small_balanced
dataset_type: dataset_small_balanced
# Dataset_small:
classes: 1, 2, 8, 11, 12, 18
# Dataset_small_balanced:
samples_per_class: 1000
remove_no_nyu: True

[datamodule]
batch_size: 64
num_workers: 1

[model]
model_name_help: CustomGCN, GIN
optimizer_help: Adam, SGD, AdamW

# Model
model_name: GIN
hidden_channels: 20
num_layers: 3
dropout: 0.5

# Optimizer
optimizer: Adam
# For SGD:
lr: 0.001
sgd_momentum: 0.8
weight_decay: 0
scheduler_gamma: 0.9

# Loss function
criterion: CrossEntropyLoss

[trainer]
epochs: 200

[wandb]
log: True
plot_inputs: False
project_name: ml-hypersim-report
run_name: GIN_3conv_20h_d05_1000x6x_lr0001_NEWDATASET_SOFTMAX